management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dcbapp
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://v000557.fhnw.ch/realms/FHNW-LST-MI
server:
  http2: 
    enabled: true
  compression:
    enabled: true 
    servlet:
        context-path: "/server"
  port: 8080
