/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TagManagementLazyImport = createFileRoute('/tagManagement')()
const DetailViewLazyImport = createFileRoute('/detailView')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TagManagementLazyRoute = TagManagementLazyImport.update({
  path: '/tagManagement',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tagManagement.lazy').then((d) => d.Route))

const DetailViewLazyRoute = DetailViewLazyImport.update({
  path: '/detailView',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/detailView.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/detailView': {
      preLoaderRoute: typeof DetailViewLazyImport
      parentRoute: typeof rootRoute
    }
    '/tagManagement': {
      preLoaderRoute: typeof TagManagementLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DetailViewLazyRoute,
  TagManagementLazyRoute,
])

/* prettier-ignore-end */
