global:
  scrape_interval: 30s


scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['server-api:8080']
    metrics_path: '/server/actuator/prometheus'

  - job_name: 'orthanc'
    static_configs:
      - targets: ['orthanc:8042']
    metrics_path: '/instances'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

